//
//  ProfileInteractor.swift
//  Architecture Design
//
//  Created by lidan on 2024/2/8.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class ProfileInteractor {
}

// MARK: - Extensions -

extension ProfileInteractor: ProfileInteractorInterface {
}
