//
//  ProfileInterfaces.swift
//  Architecture Design
//
//  Created by lidan on 2024/2/8.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol ProfileWireframeInterface: WireframeInterface {
}

protocol ProfileViewInterface: ViewInterface {
}

protocol ProfilePresenterInterface: PresenterInterface {
}

protocol ProfileInteractorInterface: InteractorInterface {
}
