//
//  DiscardInterfaces.swift
//  Architecture Design
//
//  Created by lidan on 2024/2/8.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

protocol DiscardWireframeInterface: WireframeInterface {
}

protocol DiscardViewInterface: ViewInterface {
}

protocol DiscardPresenterInterface: PresenterInterface {
}

protocol DiscardInteractorInterface: InteractorInterface {
}
