//
//  DiscardPresenter.swift
//  Architecture Design
//
//  Created by lidan on 2024/2/8.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DiscardPresenter {

    // MARK: - Private properties -

    private unowned let view: DiscardViewInterface
    private let interactor: DiscardInteractorInterface
    private let wireframe: DiscardWireframeInterface

    // MARK: - Lifecycle -

    init(
        view: DiscardViewInterface,
        interactor: DiscardInteractorInterface,
        wireframe: DiscardWireframeInterface
    ) {
        self.view = view
        self.interactor = interactor
        self.wireframe = wireframe
    }
}

// MARK: - Extensions -

extension DiscardPresenter: DiscardPresenterInterface {
}
