//
//  DiscardWireframe.swift
//  Architecture Design
//
//  Created by lidan on 2024/2/8.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

final class DiscardWireframe: BaseWireframe<DiscardViewController> {

    // MARK: - Private properties -

    // MARK: - Module setup -

    init() {
        let moduleViewController = DiscardViewController()
        super.init(viewController: moduleViewController)

        let interactor = DiscardInteractor()
        let presenter = DiscardPresenter(view: moduleViewController, interactor: interactor, wireframe: self)
        moduleViewController.presenter = presenter
    }

}

// MARK: - Extensions -

extension DiscardWireframe: DiscardWireframeInterface {
}
