//
//  DiscardInteractor.swift
//  Architecture Design
//
//  Created by lidan on 2024/2/8.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

final class DiscardInteractor {
}

// MARK: - Extensions -

extension DiscardInteractor: DiscardInteractorInterface {
}
